/**
 * Textos de interfaz en español de la plantilla de guías de socios y de la
 * página de lecturas. Reescritura nativa, no traducción palabra por palabra
 * (.claude/CLAUDE.md, sección 6). Compass, Tmall, Douyin, TP y DP no se tocan.
 */
import type { GuideUi } from '../ui';

export const ui: GuideUi = {
  dateLocale: 'es-ES',
  home: 'Inicio',
  findPartner: 'Encontrar un socio',
  scroll: 'Bajar',
  onThisPage: 'En esta página',
  chapters: {
    answer: 'En resumen',
    who: 'A quién contrata',
    where: 'Dónde buscar',
    checks: 'Comprobaciones',
    mistakes: 'Qué sale mal',
    compass: 'Cómo lo hacemos',
    faq: 'Preguntas frecuentes',
  },
  tag30s: 'En 30 segundos',
  reviewedBefore: 'Revisado por última vez el',
  reviewedAfter: ' por el equipo Compass de TheChinaPath',
  guideCoversAria: 'Qué cubre esta guía',
  whatsInGuide: 'Qué encontrará en esta guía',
  previous: 'Anterior',
  next: 'Siguiente',
  ourRoute: 'Nuestra vía',
  meterOf: 'de',
  meterChecked: 'comprobadas',
  meterHint: 'Márquelas a medida que avance. El progreso se guarda en este navegador.',
  meterWin: 'Todo comprobado. Pase a las condiciones.',
  meterReset: 'Desmarcar todo',
  termSheet: 'Hoja de condiciones',
  draftStamp: 'Borrador',
  factPaid: 'Solo nos pagan las marcas para las que trabajamos. Nadie ha comprado su lugar en la lista corta.',
  exploreCompass: 'Descubrir Compass',
  howWeWork: 'Cómo trabajamos',
  askTitle: '¿Se nos ha escapado alguna pregunta?',
  askBody: 'Plantéela en la primera llamada y le responderemos con franqueza.',
  keepReading: 'Siga leyendo',
  moreTitle: 'Más sobre cómo encontrar un socio en China',
  kindGuide: 'Guía',
  readGuide: 'Leer la guía',
  kindInsight: 'Análisis',
  readArticle: 'Leer el artículo',
  kindInsights: 'Análisis',
  hubTitle: 'Todos los artículos sobre cómo encontrar un socio',
  hubLine: 'Todo lo que hemos publicado sobre cómo encontrar un socio en China.',
  seeAll: 'Verlos todos',
  closingNames: 'De tres a cinco nombres, cada uno con una nota sobre sus fortalezas y sus flaquezas.',
  closingIntros: 'Presentaciones a empresas que ya nos conocen.',
  closingNoCommission: 'Ninguna comisión de los socios. Nunca.',
  stepAlts: [
    'Una responsable de marca toma notas a mano durante un briefing por videollamada',
    'Un consultor traza una ruta sobre un mapa de China junto a fichas de socios impresas',
    'Una responsable de marca estrecha la mano de un directivo de distribución en una sala de reuniones de Shanghái',
  ],
  guides: {
    distributor: {
      label: 'Encontrar un distribuidor',
      line: 'El distribuidor que conviene ya vende su categoría en las cadenas que usted busca. Dónde encontrar candidatos, ocho comprobaciones antes de firmar y qué condiciones pactar.',
      channel: 'Venta online y tienda física',
    },
    tp: {
      label: 'Encontrar un Tmall Partner (TP)',
      line: 'Un Tmall Partner gestiona su tienda a diario. Qué hace un TP, cómo cobra, siete comprobaciones que se hacen desde un portátil y dónde se tuercen los contratos.',
      channel: 'Tmall o Tmall Global',
    },
    dp: {
      label: 'Encontrar un Douyin Partner (DP)',
      line: 'Un Douyin Partner gestiona su tienda y sus directos. Cuánto cuesta un DP, cómo evaluarlo por sus emisiones y qué cuentas deben seguir siendo suyas.',
      channel: 'Directos y vídeo corto en Douyin',
    },
  },
  inChina: 'en China',
  hub: {
    title: 'Encontrar un socio en China | TheChinaPath',
    description:
      'Cómo elegir y verificar un distribuidor, un Tmall Partner o un Douyin Partner en China, y qué firmar. Del equipo que prepara nuestras listas cortas de Compass.',
    eyebrow: 'Encontrar un socio · Análisis',
    h1: 'Encontrar un socio en China',
    lead: 'Cómo elegir un distribuidor, un Tmall Partner o un Douyin Partner en China, y cómo verificarlo antes de firmar. Escrito por el equipo que está detrás de Compass.',
    readArticles: 'Leer los artículos',
    statArticles: 'Artículos',
    statMinutes: 'Minutos de lectura',
    statLatest: 'Último',
    articlesEyebrow: 'Análisis',
    articlesTitle: 'Todos los artículos sobre cómo encontrar un socio',
    freshBefore: 'Primero, lo más reciente. Última publicación:',
    freshAfter: '.',
    empty: 'Pronto habrá más artículos. Entretanto, las tres guías del menú son el mejor punto de partida.',
    filterAria: 'Filtrar por tema',
    all: 'Todos',
    topics: {
      distributors: 'Distribuidores',
      tp: 'Tmall Partners',
      dp: 'Douyin Partners',
      contracts: 'Contratos y condiciones',
      checks: 'Verificación',
      managing: 'Gestionar a un socio',
    },
    latest: 'Lo último',
    minRead: 'min de lectura',
    ctaEyebrow: 'Escríbanos',
    ctaTitle: '¿No sabe qué socio necesita?',
    ctaBody:
      'Cuéntenos qué vende y dónde. En la primera llamada le diremos qué tipo de socio le conviene y si tenemos alguno en nuestra base. Trabajamos por proyecto y presupuestamos después de esa llamada.',
    ctaPrimary: 'Pedir una lista corta',
    ctaSecondary: 'Ver cómo trabajamos',
  },
};
