/**
 * Deutsche Oberflächentexte für die Vorlage der Partner-Leitfäden und die
 * Leseliste zur Partnersuche. Register: Wirtschaftsressort, Sie-Anrede.
 * Marken- und Produktnamen (Compass, Tmall, Douyin, TP, DP) bleiben unverändert.
 * Die Bildtexte in stepAlts entsprechen bewusst denen in compass/de.ts.
 */
import type { GuideUi } from '../ui';

export const ui: GuideUi = {
  dateLocale: 'de-DE',
  home: 'Startseite',
  findPartner: 'Partner finden',
  scroll: 'Scrollen',
  onThisPage: 'Auf dieser Seite',
  chapters: {
    answer: 'Kurzantwort',
    who: 'Die Rolle',
    where: 'Die Suche',
    checks: 'Prüfpunkte',
    mistakes: 'Fallstricke',
    compass: 'Unser Vorgehen',
    faq: 'FAQ',
  },
  tag30s: 'Das Wichtigste in 30 Sekunden',
  reviewedBefore: 'Stand:',
  reviewedAfter: ', geprüft vom Compass-Team bei TheChinaPath',
  guideCoversAria: 'Themen dieses Leitfadens',
  whatsInGuide: 'Das steht in diesem Leitfaden',
  previous: 'Zurück',
  next: 'Weiter',
  ourRoute: 'Unser Weg',
  meterOf: 'von',
  meterChecked: 'abgehakt',
  meterHint: 'Haken Sie einen Punkt nach dem anderen ab. Der Fortschritt wird nur in diesem Browser gespeichert.',
  meterWin: 'Alles abgehakt. Weiter zu den Konditionen.',
  meterReset: 'Häkchen löschen',
  termSheet: 'Term Sheet',
  draftStamp: 'Entwurf',
  factPaid: 'Bezahlt werden wir ausschließlich von den Marken, für die wir arbeiten. Kein Name auf Ihrer Auswahlliste hat sich seinen Platz gekauft.',
  exploreCompass: 'Compass kennenlernen',
  howWeWork: 'So arbeiten wir',
  askTitle: 'Ihre Frage fehlt?',
  askBody: 'Stellen Sie sie im ersten Gespräch. Sie bekommen eine offene Antwort.',
  keepReading: 'Weiterlesen',
  moreTitle: 'Mehr zur Partnersuche in China',
  kindGuide: 'Leitfaden',
  readGuide: 'Leitfaden lesen',
  kindInsight: 'Analyse',
  readArticle: 'Artikel lesen',
  kindInsights: 'Analysen',
  hubTitle: 'Alle Beiträge zur Partnersuche',
  hubLine: 'Alles, was wir bisher zur Partnersuche in China veröffentlicht haben.',
  seeAll: 'Zur Übersicht',
  closingNames: 'Drei bis fünf Namen, jeder mit einer Einschätzung seiner Stärken und Schwächen.',
  closingIntros: 'Persönliche Vorstellung bei Unternehmen, die uns bereits kennen.',
  closingNoCommission: 'Von Partnern nehmen wir keine Provision. Nie.',
  stepAlts: [
    'Eine Markenmanagerin macht handschriftliche Notizen während eines Briefings per Video',
    'Ein Berater zeichnet eine Route auf einer China-Karte ein, daneben ausgedruckte Partnerprofile',
    'Eine Markenmanagerin gibt einem Vertriebsvorstand in einem Besprechungsraum in Shanghai die Hand',
  ],
  guides: {
    distributor: {
      label: 'So finden Sie einen Distributor',
      line: 'Ein guter Distributor verkauft Ihre Kategorie schon heute an die Händler, auf die Sie zielen. Wo Marken Kandidaten finden, welche acht Prüfungen vor der Unterschrift anstehen und welche Konditionen Sie festzurren sollten.',
      channel: 'Online- und Filialhandel',
    },
    tp: {
      label: 'So finden Sie einen Tmall Partner (TP)',
      line: 'Ein Tmall Partner führt Ihren Store im Tagesgeschäft. Was TPs leisten, wie sie verdienen, sieben Prüfungen am Laptop und die typischen Bruchstellen im Vertrag.',
      channel: 'Tmall oder Tmall Global',
    },
    dp: {
      label: 'So finden Sie einen Douyin Partner (DP)',
      line: 'Ein Douyin Partner betreibt Shop und Livestreams. Was DPs kosten, wie Sie einen an seinen Streams messen und welche Accounts Ihnen gehören müssen.',
      channel: 'Douyin: Livestream und Kurzvideo',
    },
  },
  inChina: 'in China',
  hub: {
    title: 'Partner in China finden: alle Analysen | TheChinaPath',
    description:
      'Wie Sie in China einen Distributor, Tmall Partner oder Douyin Partner auswählen, prüfen und vertraglich binden. Vom Team hinter den Compass-Auswahllisten.',
    eyebrow: 'Partner finden · Analysen',
    h1: 'Partner in China finden',
    lead: 'Wie Sie in China den richtigen Distributor, Tmall Partner oder Douyin Partner auswählen und vor der Unterschrift auf Herz und Nieren prüfen. Vom Team hinter Compass.',
    readArticles: 'Zu den Artikeln',
    statArticles: 'Artikel',
    statMinutes: 'Minuten Lektüre',
    statLatest: 'Zuletzt erschienen',
    articlesEyebrow: 'Analysen',
    articlesTitle: 'Alle Beiträge zur Partnersuche',
    freshBefore: 'Die neuesten zuerst. Zuletzt ergänzt am',
    freshAfter: '.',
    empty: 'Weitere Beiträge sind in Arbeit. Bis dahin bieten die drei Leitfäden im Menü den besten Einstieg.',
    filterAria: 'Nach Thema filtern',
    all: 'Alle',
    topics: {
      distributors: 'Distributoren',
      tp: 'Tmall Partner',
      dp: 'Douyin Partner',
      contracts: 'Verträge und Konditionen',
      checks: 'Due Diligence',
      managing: 'Partner führen',
    },
    latest: 'Neu',
    minRead: 'Min. Lesezeit',
    ctaEyebrow: 'Kontakt',
    ctaTitle: 'Welcher Partner passt zu Ihnen?',
    ctaBody:
      'Sagen Sie uns, was Sie verkaufen und wo. Im ersten Gespräch klären wir, welche Art von Partner infrage kommt und ob wir einen passenden in der Datenbank haben. Wir arbeiten projektbezogen, das Angebot folgt nach diesem Gespräch.',
    ctaPrimary: 'Auswahlliste anfordern',
    ctaSecondary: 'So arbeiten wir',
  },
};
